# Generated by Django 4.2.4 on 2023-08-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('version', models.CharField(choices=[('0', 'Malla V5'), ('1', 'Electivo'), ('2', 'Especialización')], default='Malla V5', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50)),
                ('dificultad', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('comentario', models.CharField(max_length=900)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramos.ramos')),
            ],
        ),
    ]
