# Generated by Django 4.2.4 on 2023-08-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramos',
            name='version',
            field=models.CharField(choices=[(1, 'Malla V5'), (0, 'Electivo')], default='Malla V5', max_length=10),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
