# Generated by Django 4.2.4 on 2023-08-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramos', '0002_ramos_version_alter_ramos_codigo_alter_ramos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramos',
            name='version',
            field=models.CharField(choices=[('1', 'Malla V5'), ('0', 'Electivo')], default='Malla V5', max_length=10),
        ),
    ]
