# Generated by Django 4.2.4 on 2023-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramos', '0003_alter_ramos_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50)),
                ('dificultad', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('comentario', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='ramos',
            name='version',
            field=models.CharField(choices=[('0', 'Malla V5'), ('1', 'Electivo'), ('2', 'Especialización')], default='Malla V5', max_length=10),
        ),
    ]
