# Generated by Django 4.2.4 on 2023-08-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramos', '0004_contenido_alter_ramos_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ramos.ramos'),
        ),
    ]
