# Generated by Django 4.2.4 on 2023-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramos', '0006_remove_contenido_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='comentario',
            field=models.CharField(max_length=900),
        ),
    ]
