# Generated by Django 4.2.4 on 2023-08-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramos', '0007_alter_contenido_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
