# Generated by Django 4.2.4 on 2023-08-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramos', '0008_delete_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('dificultad', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('comentario', models.CharField(max_length=900)),
            ],
        ),
    ]
